checksumBehavior: throw

enableColors: true

enableGlobalCache: true

enableProgressBars: false

enableScripts: true

enableStrictSsl: true

enableTelemetry: false

httpRetry: 3

httpTimeout: 300000

networkConcurrency: 100

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

yarnPath: .yarn/releases/yarn-4.9.4.cjs
