export {
	type AuthResult,
	sendPasswordReset,
	signInWithEmail,
	signInWithGoogle,
	signOut,
	signUpWithEmail,
	subscribeToAuthState,
} from './auth'
export { app, getFirebaseApp, getFirebaseAuth } from './config'
// Firestore
export {
	type AssetDocument,
	Collections,
	db,
	type GenerationDocument,
	getAsset,
	getGeneration,
	getModel,
	getStoreById,
	type ModelDocument,
	type StoreDocument,
	subscribeToAssets,
	subscribeToGenerations,
	subscribeToModels,
	subscribeToStores,
} from './firestore'
// Cloud Functions
export {
	approveCalibration,
	type BackgroundType,
	type CameraFraming,
	type CreateGenerationInput,
	type CreateGenerationResult,
	type CreateModelInput,
	type CreateModelResult,
	type CreateStoreInput,
	type CreateStoreResult,
	type CustomCameraSettings,
	type CustomLightingSettings,
	confirmUpload,
	createGeneration,
	createModel,
	createStore,
	deleteAsset,
	type Expression,
	functions,
	getDownloadUrl,
	getMyStores,
	getStore,
	// Fashion configuration types (expanded)
	type LightingPreset,
	type PoseStyle,
	type PostProcessingStyle,
	type ProductCategory,
	processGeneration,
	type RequestUploadUrlInput,
	type RequestUploadUrlResult,
	rejectCalibration,
	requestUploadUrl,
	type StartCalibrationInput,
	type StartCalibrationResult,
	startCalibration,
	updateStoreSettings,
} from './functions'
// Storage
export { storage } from './storage'
